### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by ComicalCache** [Montori/Bottius#76]
No files changed, compiled without problems...

`(node:12764) UnhandledPromiseRejectionWarning: QueryFailedError: SQLITE_ERROR: 10 values for 11 columns
    at new QueryFailedError (C:\Dev\Bottius\node_modules\typeorm\error\QueryFailedError.js:11:28)      
    at handler (C:\Dev\Bottius\node_modules\typeorm\driver\sqlite\SqliteQueryRunner.js:48:38)
    at Statement.errBack (C:\Dev\Bottius\node_modules\sqlite3\lib\sqlite3.js:16:21)
(node:12764) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag ´--unhandled-rejections=strict´ (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12764) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:12764) UnhandledPromiseRejectionWarning: QueryFailedError: SQLITE_ERROR: no such table: delayed_task
    at new QueryFailedError (C:\Dev\Bottius\node_modules\typeorm\error\QueryFailedError.js:11:28)
    at handler (C:\Dev\Bottius\node_modules\typeorm\driver\sqlite\SqliteQueryRunner.js:48:38)
    at replacement (C:\Dev\Bottius\node_modules\sqlite3\lib\trace.js:19:31)
    at Statement.errBack (C:\Dev\Bottius\node_modules\sqlite3\lib\sqlite3.js:16:21)
(node:12764) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag ´--unhandled-rejections=strict´ (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)`

Running it with --unhandled-rejections=strict flag set: (No idea why the formating is broken)
`C:\Dev\Bottius\node_modules\typeorm\error\QueryFailedError.js:11
        var _this = _super.call(this) || this;
                           ^

QueryFailedError: SQLITE_ERROR: 10 values for 11 columns
    at new QueryFailedError (C:\Dev\Bottius\node_modules\typeorm\error\QueryFailedError.js:11:28)
    at handler (C:\Dev\Bottius\node_modules\typeorm\driver\sqlite\SqliteQueryRunner.js:48:38)
    at Statement.errBack (C:\Dev\Bottius\node_modules\sqlite3\lib\sqlite3.js:16:21) {
  errno: 1,
  code: 'SQLITE_ERROR',
  query: 'INSERT INTO "temporary_user"("id", "discordID", "addedDate", "lastMessage", "totalMessages", "totalPings", "headPats", "xp", "permissionLevel", "partitionId", "birthdate") SELECT "id", "discordID", "addedDate", "lastMessage", "totalMessages", "totalPings", "headPats", "xp", "permissionLevel", "partitionId" FROM "user"',
  parameters: []
}`

**Comment by ComicalCache** [comment]
Birthday migration issue, corrupt DB query
